apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.5.1
    chart: grafana
    helm:
      values: |
        adminPassword: "admin" # Change this in production!
        persistence:
          enabled: false # Keeps it lightweight for testing. Data resets if restarted.
        
        # Automatically connect Grafana directly to your Loki Gateway
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki-gateway.monitoring.svc.cluster.local:80
              jsonData:
                maxLines: 1000
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true