apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.27.0
    chart: loki
    helm:
      values: |
        loki:
          auth_enabled: false
          singleBinary:
            replicas: 1
          # These storage configurations prevent the 'nil pointer' error
          storage:
            type: 'filesystem'
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
            filesystem:
              chunks_directory: /tmp/loki/chunks
              rules_directory: /tmp/loki/rules
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          server:
            http_listen_port: 3100
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true