replicaCount: 10

image:
  repository: nginxdemos/hello
  tag: plain-text
  pullPolicy: IfNotPresent
  containerPort: 80

serviceAccount:
  name: redemption-api-sa
  roleArn: "arn:aws:iam::123456789012:role/redemption-api-irsa-role"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

# --- FIXED INGRESS BLOCK ---
ingress:
  className: nginx
  host: app.test-env.internal
  path: /                  # Added base path routing definition


hpa:
  minReplicas: 3           
  maxReplicas: 50         
  targetCPU: 60
  targetMemory: 70


argocd:
  enabled: true            # Moved completely out of the HPA block to the root level